databases:
  - name: portfolio_db
    region: singapore
    plan: free
    databaseName: portfolio_db
    user: admin

services:
  - type: web
    name: portfolio_web
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true