# Generated by Django 4.2 on 2024-06-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_software_technical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='place',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='place',
        ),
    ]
