# Generated by Django 4.2.9 on 2024-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_education_place_remove_experience_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': '学歴', 'verbose_name_plural': '学歴'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': '職歴', 'verbose_name_plural': '職歴'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロフィール', 'verbose_name_plural': 'プロフィール'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'ソフトウェア', 'verbose_name_plural': 'ソフトウェア'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'スキル', 'verbose_name_plural': 'スキル'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': '業務/作品', 'verbose_name_plural': '業務/作品'},
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AddField(
            model_name='software',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AddField(
            model_name='technical',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
    ]
