# Generated by Django 4.2.9 on 2024-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_work_description_alter_work_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'ソフトウェアスキル', 'verbose_name_plural': 'ソフトウェアスキル'},
        ),
        migrations.AlterModelOptions(
            name='technical',
            options={'verbose_name': 'テクニカルスキル', 'verbose_name_plural': 'テクニカルスキル'},
        ),
        migrations.AlterField(
            model_name='software',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='レベル'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='level',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='レベル'),
        ),
    ]
