# Generated by Django 4.2.9 on 2024-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_software_options_alter_technical_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='language',
            field=models.CharField(default='ja', max_length=3, verbose_name='言語'),
        ),
        migrations.AddField(
            model_name='experience',
            name='language',
            field=models.CharField(default='ja', max_length=3, verbose_name='言語'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='ja', max_length=3, verbose_name='言語'),
        ),
        migrations.AddField(
            model_name='software',
            name='language',
            field=models.CharField(default='ja', max_length=3, verbose_name='言語'),
        ),
        migrations.AddField(
            model_name='technical',
            name='language',
            field=models.CharField(default='ja', max_length=3, verbose_name='言語'),
        ),
        migrations.AddField(
            model_name='work',
            name='language',
            field=models.CharField(default='ja', max_length=3, verbose_name='言語'),
        ),
    ]
