name: Python Tests

on:
  push:
    branches:
      - feature/github-action

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: portfolio_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Print working directory
        run: pwd

      - name: List files
        run: ls -al

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rename .env_example to .env
        run: mv .env.github .env

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: |
          python manage.py migrate

      - name: Load seed data
        run: |
          python myapp/commands/load_seed.py

      - name: Run tests with pytest
        run: |
          pytest